Timeuuid can be initialized from UUID string
datastax/php-driver pull request #113
Opened 2017-06-16 15:25 UTC by zacek

The current \Cassandra\Timeuuid object has one drawback - it cannot be reconstructed from the string. The C driver supports this but not the PHP extension. In our project we are passing Timeuuid as string via gearman job and this missing functionality is a big problem for us.

Please consider extending the object to support it.

2017-07-19 13:14 UTC, zacek commented
Could you give me some feedback, please? Usually you are responding very quickly. Is there something wrong with the pull request or is it just the summer time?
Thanks.

2017-07-25 14:44 UTC, stamhankar999 requested changes
I think this looks very good. Just add the requested test and we'll go from there. I'm not an expert on uuid's so I'd like @mpenick to also check this out and make sure he's happy with it.

2017-07-25 14:44 UTC, stamhankar999 commented on tests/unit/Cassandra/TimeUuidTest.php
> +    }
Can you add a test case for constructing with a different type of object (say a `DateTime`) to verify the `default` case of your switch?

2017-07-25 17:25 UTC, zacek commented
done, test added

2017-08-01 15:51 UTC, stamhankar999 approved these changes

2017-08-01 16:22 UTC, merged