Static build
datastax/php-driver pull request #121
Opened 2017-09-29 10:28 UTC by Skunnyk

This fix the static build of the extension inside php

2017-10-10 19:31 UTC, mikefero requested changes
Thanks for the contribution and nice catch! Just a couple of requested changes.

2017-10-10 19:31 UTC, mikefero commented on ext/config.m4
> +  PHP_CASSANDRA_FOUND_PHP_VERSION=`echo "$PHP_VERSION"`
No reason to `echo` here; simply assign the `PHP_CASSANDRA_FOUND_PHP_VERSION` variable.

2017-10-10 19:31 UTC, mikefero commented on ext/php_driver.h
> +#define phpext_cassandra_ptr cassandra_module_ptr
Could you please update `#define cassandra_module_ptr &php_driver_module_entry` => **`#define phpext_cassandra_ptr &php_driver_module_entry`** and then remove **`#define phpext_cassandra_ptr cassandra_module_ptr`**.

2017-10-11 09:22 UTC, Skunnyk commented
Thank you for the review. 
PR updated

2017-10-11 12:51 UTC, mikefero commented
Thank you for the quick turnaround. The failing tests on TravisCI are nothing to worry about right now; a fix for that will come in later in the week.

Squashing and merging PR.

2017-10-11 12:55 UTC, merged