update installation instructions
datastax/php-driver pull request #124
Opened 2018-02-15 12:52 UTC by alexott

There was no link to download server (broken link), and there was no explicit mention of dependency on the binary packages for C++ driver.

2018-02-15 14:55 UTC, mikefero requested changes
Great catch on the broken link 👍

2018-02-15 14:55 UTC, mikefero commented on README.md
> +its dependencies, so you may need to install them as well). The
The new additions in `()`'s feels a little breathy; what do you think about breaking it up into a __Note__ like the following:

```
Binary versions of the driver, available for multiple operating systems and
multiple versions of PHP, can be obtained from [DataStax download server].
The source code is made available via [GitHub]. __If you're using
[DataStax Enterprise] use the [DSE PHP driver] instead__.

__Note__: The driver extension is a wrapper around the
          [DataStax C/C++ Driver for Apache Cassandra] and is a requirement for
          proper installation of the PHP extension binaries. Ensure these
          dependencies are met before proceeding.
```

2018-02-15 17:03 UTC, alexott commented
Sure, will commit shortly

2018-06-26 19:09 UTC, mikefero commented
Thanks @alexott; landed 919cef0.

2018-06-26 19:09 UTC, closed without merging